/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JCheckBox;

/**
 *
 * @author rhtuf
 */
public class View1 extends javax.swing.JFrame {

    /**
     * Creates new form View1
     */
    public View1() {
        initComponents();
    }

    public JCheckBox getDiarrea() {
        return Diarrea;
    }

    public void setDiarrea(JCheckBox Diarrea) {
        this.Diarrea = Diarrea;
    }

    public JCheckBox getDolor() {
        return Dolor;
    }

    public void setDolor(JCheckBox Dolor) {
        this.Dolor = Dolor;
    }

    public JButton getEnviar() {
        return Enviar;
    }

    public void setEnviar(JButton Enviar) {
        this.Enviar = Enviar;
    }

    public JCheckBox getFiebre() {
        return Fiebre;
    }

    public void setFiebre(JCheckBox Fiebre) {
        this.Fiebre = Fiebre;
    }

    public JCheckBox getOlfato() {
        return Olfato;
    }

    public void setOlfato(JCheckBox Olfato) {
        this.Olfato = Olfato;
    }

    public JCheckBox getTos() {
        return Tos;
    }

    public void setTos(JCheckBox Tos) {
        this.Tos = Tos;
    }

    public JButton getButtonMostrar() {
        return buttonMostrar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fiebre = new javax.swing.JCheckBox();
        Tos = new javax.swing.JCheckBox();
        Diarrea = new javax.swing.JCheckBox();
        Dolor = new javax.swing.JCheckBox();
        Olfato = new javax.swing.JCheckBox();
        Enviar = new javax.swing.JButton();
        buttonMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fiebre.setText("Fiebre");

        Tos.setText("Tos");

        Diarrea.setText("Diarrea");

        Dolor.setText("Dolor Muscular");

        Olfato.setText("Pérdida Olfato");

        Enviar.setText("Enviar");

        buttonMostrar.setText("Mostrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Fiebre)
                .addGap(18, 18, 18)
                .addComponent(Tos)
                .addGap(18, 18, 18)
                .addComponent(Diarrea)
                .addGap(18, 18, 18)
                .addComponent(Dolor)
                .addGap(18, 18, 18)
                .addComponent(Olfato)
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(Enviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonMostrar)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fiebre)
                    .addComponent(Tos)
                    .addComponent(Diarrea)
                    .addComponent(Dolor)
                    .addComponent(Olfato))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Enviar)
                    .addComponent(buttonMostrar))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Diarrea;
    private javax.swing.JCheckBox Dolor;
    private javax.swing.JButton Enviar;
    private javax.swing.JCheckBox Fiebre;
    private javax.swing.JCheckBox Olfato;
    private javax.swing.JCheckBox Tos;
    private javax.swing.JButton buttonMostrar;
    // End of variables declaration//GEN-END:variables
}
