REM ************ TABLAS_CONJUNTOS

REM ************ TABLA ALUM, NUEVOS, ANTIGUOS ************

DROP TABLE ALUM cascade constraints;
DROP TABLE NUEVOS cascade constraints;
DROP TABLE ANTIGUOS cascade constraints;

Create TABLE ALUM
(
  NOMBRE VARCHAR2(20),
 EDAD NUMBER(2),
 LOCALIDAD VARCHAR2(15)
) ;

Create TABLE  NUEVOS
(
  NOMBRE  VARCHAR2(20),
 EDAD NUMBER(2),
 LOCALIDAD VARCHAR2(15)
) ;

Create TABLE ANTIGUOS
(
  NOMBRE  VARCHAR2(20),
 EDAD NUMBER(2),
 LOCALIDAD VARCHAR2(15)
) ;

INSERT INTO ALUM VALUES('JUAN',18,'COSLADA');
INSERT INTO ALUM VALUES('PEDRO',19,'COSLADA');
INSERT INTO ALUM VALUES('ANA',17,'ALCAL�');
INSERT INTO ALUM VALUES('LUISA',18,'TORREJ�N');
INSERT INTO ALUM VALUES('MAR�A',20,'MADRID');
INSERT INTO ALUM VALUES('ERNESTO',21,'MADRID');
INSERT INTO ALUM VALUES('RAQUEL',19,'TOLEDO');

INSERT INTO NUEVOS VALUES('JUAN',18,'COSLADA');
INSERT INTO NUEVOS VALUES('MAITE',15,'ALCAL�');
INSERT INTO NUEVOS VALUES('SOF�A',14,'ALCAL�');
INSERT INTO NUEVOS VALUES('ANA',17,'ALCALA');
INSERT INTO NUEVOS VALUES('ERNESTO',21,'MADRID');

INSERT INTO ANTIGUOS VALUES('MAR�A',20,'MADRID');
INSERT INTO ANTIGUOS VALUES('ERNESTO',21,'MADRID');
INSERT INTO ANTIGUOS VALUES('ANDR�S',26,'LAS ROZAS');
INSERT INTO ANTIGUOS VALUES('IRENE',24,'LAS ROZAS');

COMMIT;

REM ************ CONSULTAS ************

REM 1. Visualiza los nombres de los alumnos de la tabla ALUM que aparezcan en estas dos tablas: ANTIGUOS y NUEVOS.

REM 2. Escribe las distintas formas en que se puede poner la consulta anterior llegando al mismo resultado.

REM 3. Visualiza aquellos nombres de la tabla ALUM que no est�n en la tabla ANTIGUOS ni en la tabla NUEVOS.


