/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.amrv.estudios.ejerciciosmaven.t8.ejercicioCSV;

import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author marruiad
 */
public class VentanaCSV extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCSV
     */
    private final DefaultListModel<Empleado> listModel;
    private Object filter = null;
//    private static final DecimalFormat decimal = new DecimalFormat("####");

    public VentanaCSV() {
        listModel = new DefaultListModel<>();
        initComponents();
        super.setLocationRelativeTo(null);
        super.setTitle("Ejercicio CSV");
        super.pack();
        super.setMinimumSize(super.getSize());
        super.setVisible(true);
    }

    public void setListData(List<Empleado> datos) {
        listModel.clear();
        for (Empleado emp : datos) {
            if (filter == null) {
                listModel.addElement(emp);

            } else if (filter instanceof Integer) {
                if (emp.getId() == (int) filter)
                    listModel.addElement(emp);

            } else if (filter instanceof String) {
                if (emp.getNombre().contains(filter.toString()) || emp.getApellido().contains(filter.toString()))
                    listModel.addElement(emp);
            } else {
                System.out.println(">>> Otro");
                System.out.println(filter.getClass());
            }
        }
    }

    public boolean shouldDisplayID() {
        return optionID.isSelected();
    }

    public boolean shouldDisplayDepartment() {
        return optionDepartamento.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesOrdenacion = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        panelBotones = new javax.swing.JPanel();
        botonId = new javax.swing.JRadioButton();
        botonApellidos = new javax.swing.JRadioButton();
        botonDepartamento = new javax.swing.JRadioButton();
        botonCargar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        botonAgregar = new javax.swing.JButton();
        optionID = new javax.swing.JCheckBox();
        optionDepartamento = new javax.swing.JCheckBox();
        botonDesfiltrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista.setCellRenderer(new EmpleadoRender());
        lista.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lista.setFocusable(false);
        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista);
        lista.setModel(listModel);

        panelBotones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ordenar por", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelBotones.setToolTipText("");
        panelBotones.setMaximumSize(new java.awt.Dimension(235, 53));

        botonesOrdenacion.add(botonId);
        botonId.setSelected(true);
        botonId.setText("ID");
        botonId.setFocusable(false);
        botonId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIdActionPerformed(evt);
            }
        });
        panelBotones.add(botonId);

        botonesOrdenacion.add(botonApellidos);
        botonApellidos.setText("Apellidos");
        botonApellidos.setFocusable(false);
        botonApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonApellidosActionPerformed(evt);
            }
        });
        panelBotones.add(botonApellidos);

        botonesOrdenacion.add(botonDepartamento);
        botonDepartamento.setText("Departamento");
        botonDepartamento.setFocusable(false);
        botonDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDepartamentoActionPerformed(evt);
            }
        });
        panelBotones.add(botonDepartamento);

        botonCargar.setText("Cargar datos");
        botonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarActionPerformed(evt);
            }
        });

        botonBuscar.setText("Buscar empleado");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonAgregar.setText("Añadir datos");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        optionID.setSelected(true);
        optionID.setText("ID");
        optionID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionIDActionPerformed(evt);
            }
        });

        optionDepartamento.setSelected(true);
        optionDepartamento.setText("Departamento");
        optionDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionDepartamentoActionPerformed(evt);
            }
        });

        botonDesfiltrar.setText("Eliminar filtro");
        botonDesfiltrar.setVisible(false);
        botonDesfiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDesfiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optionID)
                    .addComponent(optionDepartamento)
                    .addComponent(botonDesfiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(botonDesfiltrar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonCargar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optionID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optionDepartamento)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIdActionPerformed
        Launcher.ordenarId();
    }//GEN-LAST:event_botonIdActionPerformed

    private void botonApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonApellidosActionPerformed
        Launcher.ordenarApellidos();
    }//GEN-LAST:event_botonApellidosActionPerformed

    private void botonDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDepartamentoActionPerformed
        Launcher.ordenarDepartamento();
    }//GEN-LAST:event_botonDepartamentoActionPerformed

    private void botonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarActionPerformed
        Launcher.selectFile(true);
    }//GEN-LAST:event_botonCargarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        this.filter = MessageDisplay.buscarEmpleado();
        this.setListData(Launcher.empleados);
        if (filter == null)
            this.botonDesfiltrar.setVisible(false);
        else
            this.botonDesfiltrar.setVisible(true);
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        Launcher.selectFile(false);
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged
        if (!evt.getValueIsAdjusting())
            MessageDisplay.employeeInfo(listModel.get(evt.getFirstIndex()));
    }//GEN-LAST:event_listaValueChanged

    private void optionIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionIDActionPerformed
        this.repaint();
    }//GEN-LAST:event_optionIDActionPerformed

    private void optionDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionDepartamentoActionPerformed
        this.repaint();
    }//GEN-LAST:event_optionDepartamentoActionPerformed

    private void botonDesfiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDesfiltrarActionPerformed
        this.filter = null;
        this.botonDesfiltrar.setVisible(false);
        this.setListData(Launcher.empleados);
    }//GEN-LAST:event_botonDesfiltrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JRadioButton botonApellidos;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCargar;
    private javax.swing.JRadioButton botonDepartamento;
    private javax.swing.JButton botonDesfiltrar;
    private javax.swing.JRadioButton botonId;
    private javax.swing.ButtonGroup botonesOrdenacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Empleado> lista;
    private javax.swing.JCheckBox optionDepartamento;
    private javax.swing.JCheckBox optionID;
    private javax.swing.JPanel panelBotones;
    // End of variables declaration//GEN-END:variables
}
